/** @format */

// Config actions
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE'

// Fecth actions
export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POSTS_BY_CATEGORY = 'FETCH_POSTS_BY_CATEGORY'
export const FETCH_POST_DETAIL = 'FETCH_POST_DETAIL'
export const FETCH_RECENTS = 'FETCH_RECENTS'
export const FETCH_FEATURED = 'FETCH_FEATURED'
export const FETCH_RECENTS_MORE = 'FETCH_RECENTS_MORE'
export const FETCH_FEATURED_MORE = 'FETCH_FEATURED_MORE'
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES'

// Bookmark actions
export const ADD_TO_BOOKMARK = 'ADD_TO_BOOKMARK'
export const DELETE_FROM_BOOKMARK = 'DELETE_FROM_BOOKMARK'
export const GET_BOOKMARKS = 'GET_BOOKMARKS'

// Sort actions
export const SORT_POSTS_OF_CATEGORY = 'SORT_POSTS_OF_CATEGORY'

// Search actions
export const SEARCH_ADS = 'SEARCH_ADS'
export const SEARCH_ADS_MORE = 'SEARCH_ADS_MORE'

// Toast actions
export const ADD_TOAST = 'ADD_TOAST'
export const REMOVE_TOAST = 'REMOVE_TOAST'

// User actions
export const ON_USER_STATE_CHANGED = 'ON_USER_STATE_CHANGED'
export const GET_USER_ADS = 'GET_USER_ADS'
export const GET_USER_ADS_MORE = 'GET_USER_ADS_MORE'
export const DELETE_USER_AD = 'DELETE_USER_AD'
export const SET_USER_FULL_PROFILE = "SET_USER_FULL_PROFILE"
export const SET_USER_PUSH_NOTIFICATIONS_TOKEN = "SET_USER_PUSH_NOTIFICATIONS_TOKEN"
export const GET_MEMBERS = 'GET_MEMBERS'
export const GET_MEMBERS_MORE = 'GET_MEMBERS_MORE'
export const GET_MEMBER_DETAILS = 'GET_MEMBER_DETAILS'
export const ADD_USER_LAST_VIEWS = 'ADD_USER_LAST_VIEWS'
export const CHANGE_DEFAULT_PHONE_COUNTRY_CODE = 'CHANGE_DEFAULT_PHONE_COUNTRY_CODE'
export const CHANGE_DEFAULT_COUNTRY = 'CHANGE_DEFAULT_COUNTRY'
export const CHANGE_DEFAULT_CURRENCY = 'CHANGE_DEFAULT_CURRENCY'
